### ISSUE TITLE
Question

### ISSUE THREAD

**Issue by KunChou** [JoostHoppenbrouwer/vio#1]
Hey Joost Hoppenbrouwer!

I am Kun, and I am very interested in your work. But I have some questions
1. When I run "34_posquat", it reports error: too few arguments,
2. I can't find and get understand your code of LSTM  
I am very glad if you will reply me !

**Comment by JoostHoppenbrouwer** [comment]
1. _34_posquat needs sequence as input (sh runs for all sequences)
2. LSTM is not implemented yet.

**Comment by KunChou** [comment]
Thanks for your reply!:)
Your work indeed give me lots of inspiration!
I meet a lot of difficulties when I build LSTM with tensorflow, I hope you can do a great job!

**Comment by KunChou** [comment]
Unfortunately I still have some problem with _34_posquat. 
I have recorded the data, but how can I use sequence as input. It always reports” Need more arguments
"
