### ISSUE TITLE
 The file  convert_gt.py

### ISSUE THREAD

**Issue by Ran-ZHU** [JoostHoppenbrouwer/vio#4]
Hi,  thanks for your work!
I have a question about the fuction "quat_multiply()" in the file "gt/convert_gt.py". There seems to be an error in the formula. look at the picture.
![image](https://user-images.githubusercontent.com/53015821/71510072-8e0cdf80-28c8-11ea-92b3-36b7112f5267.png)

**Comment by JoostHoppenbrouwer** [comment]
Hi,

I don't see any error. It would be helpful to mention what error you are trying to point out.

**Comment by Ran-ZHU** [comment]
This is your code in the "convert_gt.py"
![image](https://user-images.githubusercontent.com/53015821/71510395-bba65880-28c9-11ea-8d0f-14e6111abbb8.png)
I looked up a lot of relevant information. It seems to look something like this:
![image](https://user-images.githubusercontent.com/53015821/71510471-045e1180-28ca-11ea-9672-e4f79e0a8090.png)

There's a difference between the plus and minus signs

**Comment by JoostHoppenbrouwer** [comment]
It seems like you are right. However, this project has been discontinued a long time ago.
But thanks for pointing out.
